language: csharp
solution: TourDeFrance.sln
mono: latest
dotnet: 1.0.0-preview2-003121
install:
  - dotnet restore
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - dotnet build ./TourDeFrance.Tests -c Debug -f net45
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe TourDeFrance.Tests/bin/Debug/net45/TourDeFrance.Tests.dlls