# doesn't wok for now, will review it later
language: csharp
sudo: required  
dist: trusty
env:  
  - CLI_VERSION=latest
solution: TourDeFrance.sln
addons:  
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g
mono:
  - latest
os:  
  - linux
install:
  - echo "Installing dotnet"
  - export DOTNET_INSTALL_DIR="$PWD/.dotnetcli"
  - curl -sSL https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0/scripts/obtain/dotnet-install.sh | bash /dev/stdin --version "$CLI_VERSION" --install-dir "$DOTNET_INSTALL_DIR"
  - export PATH="$DOTNET_INSTALL_DIR:$PATH"  
  - dotnet restore
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - dotnet build ./TourDeFrance.Tests -c Debug -f net45
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe TourDeFrance.Tests/bin/Debug/net45/TourDeFrance.Tests.dlls